name: Scaleway Kustomize Deploy
description: Deploy to Scaleway using a Kustomize config
inputs:
  secret-key:
    description: Scaleway secret key
    required: true
  cluster-id:
    description: Scaleway Cluster ID. Can be retrieved with `scw k8s cluster list name=$CLUSTER_NAME -o template="{{.ID}}"`.
    required: true
  region:
    description: Scaleway region (e.g. "fr-par")
    required: true
  docker-namespace:
    description: Scaleway Docker registry namespace (e.g. "my-namespace")
    required: true
  kustomization-base-dir:
    description: Path to base kustomize directory
    required: true
    default: "kustomize/base"
  kustomization-dir:
    description: Path to the kustomize directory to apply / deploy (e.g. `kustomize/overlays/production`)
    required: true
  create-k8s-namespace:
    description: Create Kubernetes namespace if it does not exist
    required: true
    default: "true"
  image-name:
    description: Docker image name (e.g. `my-app`)
    required: true
  image-tag:
    description: Docker image tag to deploy (e.g. `0.9.14`)
    required: true
  age-secret-key:
    description: Secret key to decrypt deploy secrets with (e.g. `AGE-SECRET-KEY-123456`)
    required: false
  encrypted-filename:
    description: Filename/subpath inside `kustomization-dir` to a file with age encrypted secrets to decrypt
    required: true
    default: "secrets.env"
  decrypted-filename:
    description: Filename/subpath inside `kustomization-dir` to which the age encrypted secrets will be decrypted to
    required: true
    default: "secrets.env.dec"
  create-image-pull-secret:
    description: Create an image pull secret named "rg.`$region`.scw.cloud", to be referenced in `imagePullSecrets` in a k8s deployment/job
    required: true
    default: "true"
  k8s-dry-run:
    description: Used to set `kubectl` option `--dry-run` Valid values are `none` (default), `client` and `server`.
    required: true
    default: "none"

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        clean: false

    - name: Parse base kustomization.yaml
      uses: juliojimenez/yamler@a453cafd89cbb8f33e64da9a488b1d6a675209de # 0.0.12
      id: kustomization_base
      with:
        yaml-file: ${{ inputs.kustomization-base-dir }}/kustomization.yaml

    - name: Parse overlay kustomization.yaml
      uses: juliojimenez/yamler@a453cafd89cbb8f33e64da9a488b1d6a675209de # 0.0.12
      id: kustomization_overlay
      with:
        yaml-file: ${{ inputs.kustomization-dir }}/kustomization.yaml

    - name: Print steps (including output from yamler)
      shell: bash
      if: ${{ env.DEBUG == 'true' }}
      run: |
        echo '${{ toJSON(steps) }}'

    - name: Decrypt secrets with `age`
      uses: jacobsvante/age-decrypt-action@v0
      if: ${{ inputs.age-secret-key && inputs.kustomization-dir != '' && inputs.encrypted-filename != '' }}
      with:
        secret-key: ${{ inputs.age-secret-key }}
        input-file: ${{ inputs.kustomization-dir }}/${{ inputs.encrypted-filename }}
        output-file: ${{ inputs.kustomization-dir }}/${{ inputs.decrypted-filename }}

    - name: Substitute newTag
      shell: bash
      if: ${{ steps.kustomization_base.outputs.images__0__newtag }}
      env:
        IMAGE_TAG: ${{ inputs.image-tag }}
        KUSTOMIZE_FILE: ${{ inputs.kustomization-base-dir }}/kustomization.yaml
      run: |
        sed -i.bkp "s/newTag: .*/newTag: \"$IMAGE_TAG\"/g" $KUSTOMIZE_FILE

    - name: Substitute newName
      shell: bash
      if: ${{ steps.kustomization_base.outputs.images__0__newname }}
      env:
        DOCKER_SERVER: rg.${{ inputs.region }}.scw.cloud
        DOCKER_NAMESPACE: ${{ inputs.docker-namespace }}
        IMAGE_NAME: ${{ inputs.image-name }}
        KUSTOMIZE_FILE: ${{ inputs.kustomization-base-dir }}/kustomization.yaml
      run: |
        sed -i.bkp "s|newName: .*|newName: \"$DOCKER_SERVER/$DOCKER_NAMESPACE/$IMAGE_NAME\"|" $KUSTOMIZE_FILE

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3

    - name: Get kustomize output
      shell: bash
      run: |
        kubectl kustomize ${{ inputs.kustomization-dir }} > output.yaml
        cat output.yaml

    - name: Setup Scaleway kubeconfig
      shell: bash
      env:
        URL: https://api.scaleway.com/k8s/v1/regions/${{ inputs.region }}/clusters/${{ inputs.cluster-id }}/kubeconfig?dl=1
      run: |
        mkdir ~/.kube || true
        if [[ $KUBECONFIG_DOWNLOAD_DRY_RUN == 'true' ]]; then
          echo "[dry run] Would download kubeconfig from $URL and write to ~/.kube/config"
        else
          curl $URL \
            --header "X-Auth-Token: ${{ inputs.secret-key }}" \
            --fail \
            > ~/.kube/config
        fi

    - name: Create k8s namespace
      shell: bash
      if: ${{ inputs.create-k8s-namespace && steps.kustomization_overlay.outputs.namespace }}
      env:
        K8S_NAMESPACE: ${{ steps.kustomization_overlay.outputs.namespace }}
      run: |
        [[ ${{ inputs.k8s-dry-run }} != 'none' ]] \
          && echo "[dry run] Creating namespace $K8S_NAMESPACE if it doesn't exist..."
        kubectl get namespace $K8S_NAMESPACE \
        || kubectl create namespace \
            --dry-run=${{ inputs.k8s-dry-run }} \
            --output=yaml \
            $K8S_NAMESPACE

    - name: Create image pull secret
      shell: bash
      if: ${{ inputs.create-image-pull-secret == 'true' }}
      env:
        SECRET_NAME: rg.${{ inputs.region }}.scw.cloud
        K8S_NAMESPACE: ${{ steps.kustomization_overlay.outputs.namespace || 'default' }}
      run: |
        [[ ${{ inputs.k8s-dry-run }} != 'none' ]] \
          && echo "[dry run] Creating k8s docker-registry secret..."
        kubectl get secret \
          --namespace $K8S_NAMESPACE \
          $SECRET_NAME \
        || kubectl create secret docker-registry \
          $SECRET_NAME \
          --namespace $K8S_NAMESPACE \
          --docker-server=rg.${{ inputs.region }}.scw.cloud \
          --docker-username=${{ inputs.docker-namespace }} \
          --docker-password=${{ inputs.secret-key }} \
          --dry-run=${{ inputs.k8s-dry-run }} \
          --output=yaml

    - name: Deploy
      shell: bash
      run: |
        [[ ${{ inputs.k8s-dry-run }} != 'none' ]] \
          && echo "[dry run] Applying kustomization ${{ inputs.kustomization-dir }}..."
        kubectl apply \
          --kustomize=${{ inputs.kustomization-dir }} \
          --dry-run=${{ inputs.k8s-dry-run }} \
          --output=yaml
